openapi: 3.0.1
info:
  title: hydra-server
  description: Test server to demonstrate principles in the book
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Hydra Servr
    description: Example endpoints for Markdown Writer App
  - name: Specification
    description: The swagger API specification
paths:
  /articles:
    post:
      tags:
        - Articles
      description: Create a new article
      responses:
        200:
          description: Return a new article
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        201:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          description: The id of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
          example: 'ab923c'
        data:
          type: string
          example: '#hello world'
        owner:
          type: string
          example: foo|bar
        grants: 
          $ref: '#/components/schema/Grant'
    Grant:
      type: object
      properties:
        identifier: 
          type: string
          example: 'foo|bar or abhishek@example.org or @example.org'
        permissions:
          type: array
          items: 
            type: string 
    Error:
      type: object
      additionalProperties: true

    User:
      type: object
      additionalProperties: true